name: Build & Compile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (backend)
        run: |
          cd backend
          npm ci
      - name: Compile backend (TypeScript)
        run: |
          cd backend
          npm run build
      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm ci
      - name: Compile frontend (TypeScript)
        run: |
          cd frontend
          npm run build
      - name: Docker build
        run: |
          docker build .
